### ISSUE TITLE
Create monitoring alert for kubernetes storage volumes

### ISSUE THREAD

**Issue by theferrit32** [clingen-data-model/architecture#106]
When a disk for a disk in use by a kubernetes deployment nears capacity, we should receive an alert on Slack.

**Comment by sjahl** [comment]
@theferrit32 Are we looking for alerts on persistent volumes, local disk on the k8s nodes, or both?

**Comment by theferrit32** [comment]
@sjahl I think since we are using a mix of vm local disks and k8s persistent volumes we should look at both. I'm not sure how noisy the warnings will be
