### ISSUE TITLE
Review GeneTracker message structure

### ISSUE THREAD

**Issue by tnavatar** [clingen-data-model/architecture#11]
Context per TJ:

> Hi Scott and Tristan,
> 
> Some months back we used the DP Modeling call to review a schema I had put together for events that the GeneTracker would publish to the DataExchange.  My understanding is that the two expected consumers of this topic will be the GCI and the Website, so I’m sending you the updated schema.  I’ll also be discussing the schema with Rao and Matt, but in the interest of keep the conversations focused I’d like to conduct them separately.
> 
> While I know that Courtney wants to show OMIM phenotype data on the website, I’m not entirely clear on all of the other use cases that this data would need to support on the website.  If you could take a look at the schema and example message and let me know what you think I’d appreciate it.
> 
> There are couple of things I want to point out b/c they came up in the previous discussion:
> I’ve updated the “Group” field to match what I expect will be applicable once we have expert panels in a group/personnel management system (don’t-call-it-an-OMS). I’m also including the affiliation id for the group since that’s currently the unique id everyone uses.
> I know you all aren’t particularly interested in the individual curator behind a curation, but I’ve gone ahead and included it as it will be important to GT/GCI integration.  I’m proposing a “clingen_id” field which I would expect to come from the dci-OMS.
> Tristan asked about rationales the last time we spoke and wondered wether we might want to collect and provide a different data-structure for “rationales” that might link PubMed ids to particular rationales.  After consulting with the Gene Curation Small Group, it sounds like they do not want to adopt a new structure for this information.  I have grouped the list of rationales for a curation and the pmids that support the rationales into an object called “rationale".
> 
> 
> If you’d like to set up a call to discuss let me know.  Happy to do another conversation during the DP Modeling call next week if that is preferable to you all.
> 
> 
> Cheers,
> TJ

**Comment by larrybabb** [comment]
@tnavatar I'm presuming this is on hold or nothing has started. If you would provide updates here as you have them I would appreciate it.

**Comment by tnavatar** [comment]
Nothing started yet, still on my plate to do
