### ISSUE TITLE
Inventory of all confluent topics

### ISSUE THREAD

**Issue by dazzariti** [clingen-data-model/architecture#157]
We need a dump of all the topics and the following values:

Topic name
Owner
Requester (if available)

With the goal of creating a maintained list of kafka topics that we can make available across clingen

Agree on final form and required files for each topic

**Comment by sjahl** [comment]
In case we're writing a script that is expected to be usable in the future, just FYI the ccloud cli is being deprecated: https://support.confluent.io/hc/en-us/articles/4409994323220-Confluent-Cloud-CLI-deprecation-notice-ccloud-CLI-will-be-sunset-on-May-9-2022

If this is more of a one time thing, I don't think we need to worry about using ccloud.

**Comment by theferrit32** [comment]
The scraper script takes a set of cluster credentials and gets the list of all topics, their message counts, and first and last message timestamps, using the kafka java libs. 

https://github.com/clingen-data-model/data-exchange-topics/blob/846718d0d9a5e1c0a693a51190375b09ce49ac35/src/topic_utils/topic_metrics.clj

**Comment by larrybabb** [comment]
@theferrit32 will delete the marked topics from confluent and remove them from the inventory list

**Comment by larrybabb** [comment]
Let's put all these related tickets in an Epic and clarify the DoD (definition of done)

**Comment by KelseaChang5** [comment]
This is essentially done. The only thing left is to automate this, which is a [ticket on its own](https://app.zenhub.com/workspaces/genegraphdxclinvar-60340fb9898dae001107e94e/issues/clingen-data-model/data-exchange-topics/25) and has been archived for now, as not a top priority item for now and will be manually reviewed for the time being. Will close
