### ISSUE TITLE
Prepare Infra & Discussion Slides for SP 12/3 Meeting

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/architecture#176]
### Finalize draft architecture graphic to be used throughout SP meeting.
1. Meet with tech groups on Tues DM mtg to do a quick review and garner acceptance (UNC in particular)
### Create 2 Infra Slides one for Kevin and myself.
2. Kevin (LDH)
3. Me (represent MONDO notification feature process and connection to individual WS requests)
### Create Discussion slides
4. 1 on Ticket tracking process change (demonstrate by showing before and after of current issue)
We will separate Spec and Dev tickets and have one continuous flow for New/Open -> In Progress -> In Review -> Completed. with the option to put things on Hold (no clear estimates on being addressed by developers). vs Backlog (on deck or prioritized to be worked on after current in progress work - if an item sits in backlog for an entire cycle it should be re-assessed whether it should be moved to HOLD - could be a discussion point at future SP meetings).  SP meetings can be a place to highlight rationale for tickets that jump ahead of items previously on Hold or in the Backlog/Selected for Development
5. 2 Product vs Workstream centric presentations going forward? alternate? intermix? no change?

**Comment by KelseaChang5** [comment]
December 2021 Triage: Closed
