### ISSUE TITLE
Gene Suggester ability to search on aliased gene name

### ISSUE THREAD

**Issue by toneillbroad** [clingen-data-model/architecture#26]
Request from the website team to modify the Gene Suggester to not only search based on current Gene name, but to add the ability to search on previous Gene name (perhaps all aliases?). The issue here is that a Gene such as "PAFAH1B1" (new name) is more commonly known by its previous name "LIS1". The ability to search the gene suggester based on name "LIS1" but to return the reference to gene "PAFAH1B1" is desirable. Could be fairly easy to do by adding previous name entries to suggester as gene suggester is being built (assuming previous names are available in the data).

**Comment by KelseaChang5** [comment]
December 7th 2021 Triage: Closed
