### ISSUE TITLE
us-east1-b seems to be consistently out of capacity

### ISSUE THREAD

**Issue by sjahl** [clingen-data-model/architecture#393]
us-east1-b (where all of our GKE clusters and node pools) currently run, seems to be having some kind of capacity issue, and doesn't have enough compute capacity for us to launch new nodes during routine GKE upgrades. This has been the case since at least the weekend of the 18th, so we've been bumping into this for almost a week.

We should look into perhaps moving some of our clusters out of us-east1-b, or maybe changing our clusters so that nodes are launching in more than one region. The second option there might make us a little more resilient to this problem in the future.

**Comment by sjahl** [comment]
https://cloud.google.com/kubernetes-engine/docs/how-to/creating-a-zonal-cluster#single-zone_versus_multi-zonal

Multi-zonal is probably the sweet spot for us -- doesn't required the HA/Regional control plane, and thus (i believe) costs less.

**Comment by larrybabb** [comment]
@sjahl please bring this up today at the meeting so that we can prioritize/schedule this to get done asap. Thanks.

**Comment by sjahl** [comment]
After looking at this for a while -- there's only really one hard-stop way to prevent this error case, which is to reserve more instances than we actually use, so that we always have the capacity to launch the right number of nodes during an upgrade. (i.e. in a 2-node pool, we'd have to reserve at least 3 instances so that we'd guarantee the capacity to launch a new node when upgrading a pool). For our purposes and the infrequency at which we hit this error condition, the extra reservation just ends up being a waste.

Given that this condition only really causes a problem when you're trying to add nodes, or during an upgrade where the old nodes are left running and are not deleted before we hit the error, I don't think it's worth the extra insurance of reserving the nodes.

In any case, if we encounter capacity issues again, the resolution is pretty straightforward. In non-urgent situations, we just wait for capacity to return to our chosen zone, or give up on the zone and move elsewhere. In urgent situations, we just launch a new pool where capacity is available, cordon the old nodes to migrate the pods, and then spin down the old node pool.

**Comment by tnavatar** [comment]
Appreciate the research into this. Not that it’s a huge problem right now, but are there issues with interconnects across zones within the same region? Otherwise agree—would seem to add some robustness. How complicated would the migration be?

**Comment by sjahl** [comment]
I think google's claim is that network overhead between zones in the same region should be less than 1ms at the 95th percentile. So, I don't think there's anything to worry about there in terms of performance. If we schedule things in two different zones, then the risk there is that it's possible for the two zones to lose connectivity with eachother in the event of a failure on google's end. We don't have a lot of stuff (that I'm aware of) that has communication between pods in the same cluster, so the risk of this is pretty small. I think we run clusters with single-zone kubernetes control plane nodes -- in the case of severed connectivity between zones, the control plane may not be able to manage pods in a different zone, but my understanding is that running pods would stay running -- rescheduling would just start to get weird until the network is back up.

I'm not really sure there's much of a migration pattern here. The failure pattern was that we couldn't scale up a node pool because that zone it was in was out of resources. So it's possible for that to happen to any one node pool during a GKE upgrade if the zone that particular pool is in has no space.

If we wanted to increase resiliency more generally, to guard against a zone failure, i think it's as simple as just running a multi-zonal node pool, which GKE can do pretty transparently. But, again, this doesn't help with the problem of limited google capacity.
