### ISSUE TITLE
purchase instance reservations for clingen gcp projects

### ISSUE THREAD

**Issue by sjahl** [clingen-data-model/architecture#431]
Now that our GKE clusters are all running a similar instance class, I think it makes sense to purchase some instance reservations. Our compute usage is very stable, so I think it makes sense to buy reservations for everything that we can. We've been hitting 100% of our budget slightly earlier over the last few months, so this should help us shrink the budget a little bit.

**Comment by sjahl** [comment]
Hey guys,

I just purchased one year commitments for our GKE nodes (and also for a 'web2' instance in clingen-dx/prod that's always running).

Just looking through the list of other VMs, here's some that appear to be running all the time. Does anyone have thoughts on whether we should reserve these too? Basically if they're definitely going to run for the next year non-stop, we should reserve them:

** clingen-dev**
clinvar-reports-all

**clingen-stage**
dci1
web2

**clingen-dx (prod)**
dci2
backup1
aurora / clingen-dx

/cc @larrybabb @tnavatar @toneillbroad @theferrit32

**Comment by larrybabb** [comment]
@sjahl lets touch base to work Phil into these discussions.

**Comment by toneillbroad** [comment]
I am going to permanently disable clinvar-reports-all on dev. Most of the
reports don't generate anymore.

Terry

**Comment by larrybabb** [comment]
ok. I am running the genomeconnect and expert panel ones for now.
hopefully it will all be moot once I get the discrepancy report stuff deployed and in their hands.

**Comment by sjahl** [comment]
OK, with Phil's feedback, I have purchased reservations for the dci* and web*, and aurora instances.
