### ISSUE TITLE
clean up unused static IPs

### ISSUE THREAD

**Issue by sjahl** [clingen-data-model/architecture#432]
Google charges you a fee when you have reserved a static IP address, but don't have it associated with a VM (apparently if you have it attached to a _stopped_ VM, they don't charge you, though).

The fee is around $7.50/month per address. Across our 3 projects, we have the following IPs that aren't attached to anything:

**clingen-dev**

| address name | ip |
| -------------- | -- |
| ~~clingen-kb-dev-ip~~ | ~~34.75.188.251~~ |
| ~~search-dev-ip~~ | ~~35.196.187.83~~ |
| ~~wapi-dev~~ | ~~34.74.201.111~~ |
| ~~website-dev~~ | ~~35.243.217.163~~ |
| ~~anyvar-static-ip~~ | ~~34.73.173.40~~ |
| ~~clingen-ds-dev-ip~~ | ~~35.243.230.124~~ |
| ~~clingen-ds-ip~~ | ~~35.196.195.211~~ |
| ~~clinvar-dev~~ | ~~35.190.184.75~~ |
| ~~ds-dev-ip~~ | ~~35.227.25.248~~ |

**clingen-stage**

| address name | ip |
| -------------- | -- |
| ~~search1~~ | ~~34.74.251.160~~ |
| ~~clingen-ds-stage-ip~~ | ~~34.74.244.24~~ |
| ~~genegraph-clinvar-ip~~ | ~~34.120.239.227~~ |
| ~~neo4j-ip~~ | ~~35.211.217.40~~ |

**clingen-dx (prod)**

| address name | ip |
| -------------- | -- |
| ~~clingen-static-addr~~ | ~~35.231.217.39~~ |
| ~~jira1~~ | ~~34.74.142.55~~ |
| ~~genegraph-ip~~ | ~~34.74.127.4~~ |
| ~~global-prod-genegraph-prod-ip~~ | ~~34.75.154.128 (i think this might be the old genegraph static IP)~~ |

Looking for some input on whether these can just be deleted, or of we have the addresses reserved for one reason or another.

**Comment by tnavatar** [comment]
the clingen-ds-* in all environments can be deleted, as can neo4j* and any unused genegraph ones

**Comment by sjahl** [comment]
@tnavatar thanks, those should all be gone now. I also apparently missed the following IP, is this in the came category as the clingen-ds-* stuff? It's in clingen-dev

| address name | ip |
| ---------- | -------------- |
| ds-dev-ip | 35.227.25.248 |

**Comment by tnavatar** [comment]
Ahh. Can delete that one too.

**Comment by theferrit32** [comment]
I've released the `anyvar-static-ip` and `clinvar-dev` addresses in the `clingen-dev` project

**Comment by sjahl** [comment]
Ok, this is all set, thanks all!
