### ISSUE TITLE
Add terraform configuration for google logging metric and alerting

### ISSUE THREAD

**Issue by theferrit32** [clingen-data-model/architecture#49]
When logs for certain pods contain `WARN` or `ERROR` level messages, we want to be able to receive either an email or a slack message about it, maybe batched on some interval like 1 minute in case a lot of messages happen in a short time period. If any of our WARN/ERROR log messages contain sensitive information like keys then we will need to not include the logged message in the alert message, or be careful about who is allowed to receive the alerts.

We could use `clingen-alerts` (public), or a separate (private) broad/geisinger infrastructure alerts channel.

In some places we use pedestal logging library and in others we use taoensso/timbre. Unfortunately they are not using the exact same log line formatter so getting the log metric to work for both might need a regex matcher for both, if something like `" ERROR "` is too ambiguous. I think we could also modify the timbre log formatter to match the one being used in genegraph, or refactor to use pedestal logging with the same logback config file.

**Comment by theferrit32** [comment]
@sjahl It looks like Google cloud logging is detecting a severity from the log message but it doesn't look always correct. 

This is a taoensso/timbre log message that was `DEBUG` level but the cloud logging field has severity `INFO`:

```
2021-05-09 07:09:41.874 EDT 
21-05-09 11:09:41 clinvar-raw-producer-696bcf949c-w2sc4 DEBUG [clinvar-raw-producer.core:176] - Subscribed to consumer topic broad-dsp-clinvar

{
 insertId: "yf49wtg2aqs4c5"  
 
 labels: {…}  
 logName: "projects/clingen-stage/logs/stdout"  
 receiveTimestamp: "2021-05-09T11:09:50.064386297Z"  
 resource: {…}  
 severity: "INFO"  
 textPayload: "21-05-09 11:09:41 clinvar-raw-producer-696bcf949c-w2sc4 DEBUG [clinvar-raw-producer.core:176] - Subscribed to consumer topic  broad-dsp-clinvar
"  
 timestamp: "2021-05-09T11:09:41.874471375Z"  
}
```

**Comment by sjahl** [comment]
Ok. My guess here is that timbre is either not setting a real syslog priority (i.e. it's just putting the string DEBUG in the log when a `log/debug` is called), or it's setting them, but the priorities are mapped to numeric values that don't match what stackdriver is looking for.

From what I can tell, by default stackdriver will set anything going to a container's stdout to INFO, if it doesn't know what else to do with it, and stderr will get ERROR severity.

Do you think that's enough granularity for our purposes? If it's not, we can definitely go the regex route. Another possible option is seeing if timbre supports a structured output format (i.e. JSON), that will allow us to set our own values in a structure that ends up in the textPayload.

**Comment by sjahl** [comment]
@theferrit32 I think I'm going to use this issue for more general terraform config on logging and alerting, since that was the original spirit of the issue. We should create other issues re: JSON and logging format on the software projects where code changes are required to accommodate that.
