### ISSUE TITLE
Create encrypted kubernetes secrets files

### ISSUE THREAD

**Issue by theferrit32** [clingen-data-model/architecture#5]
We want to be able to track kubernetes secrets in a persistent location as code artifacts.

Mozilla SOPS is a possibility and can encrypt/decrypt using a key in GCP key management system, loading the key using local gcloud credentials.

https://github.com/mozilla/sops#encrypting-using-gcp-kms

**Comment by sjahl** [comment]
I'm iterating on a few of the secret management options here: https://github.com/broadinstitute/tgg-extsec-testing

Currently testing SOPS like we discussed, and also a different mechanism (external-secrets) which synchronizes secrets defined in the GCP Secret Manager, with kubernetes secrets inside your clusters.

I think it might to chat about what these options look like in practice from a developer perspective, and see what folks think works better.

**Comment by sjahl** [comment]
I'm imagining that I will need to perform the task of copying secrets from k8s clusters into GCP secrets at least a few times, so today I worked on a utility to do that over here: https://github.com/broadinstitute/tgg-sre-utils/blob/main/migrate_k8s_secrets/migrate_k8s_secrets.py

**Comment by sjahl** [comment]
I've removed the blocker on this since the genegraph-dev cluster should be auto deploying for now. Leaving the issue open until I migrate the secrets in stage and prod.

**Comment by sjahl** [comment]
I've migrated the staging secrets into GCP secret manager, the deployment work is in progress.

**Comment by sjahl** [comment]
The actual work for this issue should be all set -- I just synced over the secrets from the production cluster to Secret Manager. Deployment is over in #24
