### ISSUE TITLE
Add variation normalization chart to argo

### ISSUE THREAD

**Issue by theferrit32** [clingen-data-model/architecture#554]

**Comment by larrybabb** [comment]
@theferrit32 need an update on this. seems like it may be done. if not, should this be added to the GK-Pilot epic or simply backlogged or put into a "when you get annoyed enough, you may want to do this..." bucket.

**Comment by theferrit32** [comment]
Bumping the priority of this. Will also open other ticket for doing this with anyvar

**Comment by theferrit32** [comment]
Added vrs-1 version and vrs-2 version to argo via UI. Will check in application config files

**Comment by theferrit32** [comment]
Added vrs-1 version and vrs-2 version to argo via UI. Will check in application config files

**Comment by theferrit32** [comment]
Argo application files are checked in

vrs 1: https://github.com/clingen-data-model/architecture/blob/master/services/dev/argo/dev-varnorm-1.yaml
vrs 2: https://github.com/clingen-data-model/architecture/blob/master/services/dev/argo/dev-varnorm-2.yaml
