### ISSUE TITLE
Renew GCP committed use discounts

### ISSUE THREAD

**Issue by theferrit32** [clingen-data-model/architecture#566]
Current compute core and memory discounts in dev, stage, prod GCP projects end on July 14, 2023. Should be updated and renewed by then.

dev specifies only N2 cores, and stage and prod use a mix of N1 and N2

**Comment by larrybabb** [comment]
@theferrit32 I think @toneillbroad was looking into this or something related. Let's discuss at standup quickly and determine if this is done or has a timing concern.

**Comment by toneillbroad** [comment]
I spoke with Steve and he will renew the committed use discounts in a few days. After some analysis [here](https://docs.google.com/spreadsheets/d/11neS5bY6yqcG03MWcaYASjOAhJZcrNU6DuRrnXP-HLw/edit#gid=0) and discussion, we went with his recommendation.
