### ISSUE TITLE
Remove supplemented node pools in prod k8s environment

### ISSUE THREAD

**Issue by toneillbroad** [clingen-data-model/architecture#615]
Recently there as a memory issue when deploying a new genegraph release to stage and prod kubernetes environment. The issue was that Tristan had also released the new genegraph into that environment. We added a new node pool to allow us deploy. 

The old pool has been deleted from stage.
The old node-pool needs to be decomissioned ffromm prod..

**Comment by tnavatar** [comment]
I think we need to keep at least one extra node in stage, but the old node pool in prod needs to go...
