### ISSUE TITLE
Automate genegraph migration creation and update deployment with migration version and genegraph container image on push to genegraph master 

### ISSUE THREAD

**Issue by toneillbroad** [clingen-data-model/architecture#62]
Work with Steve on ideas on how to automate genegraph migration creation and update deployment with migration version and genegraph container image on push to genegraph master.

This is meant to achieve a one-to-oner relationship between migration versions and genegraph image deployments.

**Comment by sjahl** [comment]
I think we can close this one out, with production genegraph Argo-ified
